superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url = '/superheroes/'))

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superhero_project/superheroes/urls.py
from django.urls.resolvers import URLPattern
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/',views.detail, name ='detail' ),
    path('new/', views.create, name='create'),
    path('edit/<int:hero_id>/' , views.edit, name='edit'),
    path('delete/<int:hero_id>/', views.delete, name='delete')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superhero_project/superheroes/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import CharField

# Create your models here.

class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)
    image =models.ImageField(upload_to = 'superheroes_image' ,blank =True)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context ={
        'all_heroes':all_heroes
    }
    return render(request,'superheroes/index.html', context)

def detail(request,hero_id):
    single_hero = Superhero.objects.get(pk = hero_id)
    context ={
        'single_hero':single_hero
    }
    return render(request,'superheroes/detail.html', context)

def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catch_phrase = request.POST.get('catchphrase')

        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability = primary, secondary_ability= secondary, catch_phrase = catch_phrase)
        new_hero.save()

        return HttpResponseRedirect(reverse('superheroes:index'))

    else:
        return render(request,'superheroes/create.html')

def edit(request,hero_id):
    hero_to_update = Superhero.objects.get(pk = hero_id)
    context ={
        'hero_to_update':hero_to_update
    }
    
   
    if request.method == 'POST':
        update_hero = Superhero.objects.get(pk = hero_id)
        update_hero.name = request.POST.get('name')
        update_hero.alter_ego = request.POST.get('alter_ego')
        update_hero.primary_ability = request.POST.get('primary')
        update_hero.secondary_ability = request.POST.get('secondary')
        update_hero.catch_phrase = request.POST.get('catchphrase')

        
        update_hero.save()

        return HttpResponseRedirect(reverse('superheroes:detail', kwargs={'hero_id': hero_id}))
    else:
        return render(request,'superheroes/edit.html', context)

      
    
    


def delete(request,hero_id):
   
    list_hero = Superhero.objects.get(pk = hero_id)
    context1 ={
        'list_hero':list_hero
    }
    delete_hero = Superhero.objects.get(pk = hero_id)
    context ={
        'delete_hero':delete_hero
    }
    delete_hero.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))
   
    # return render(request,'superheroes/delete.html', context1)

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a New hero</title>
</head>
<body>
    <form action = "{%url 'superheroes:create'%}" method ="post">
        {%csrf_token %}

    Name:<input type ='text' name="name" id="name"><br />
    Atler Ego:<input type ='text' name="alter_ego" id="alter_ego"><br />
    Primary Ability:<input type ='text' name="primary" id="primary"><br />
    Secondary Ability:<input type ='text' name="secondary" id="secondary"><br />
    Catch Phrase:<input type ='text' name="catchphrase" id="catchprase"><br />
        <input type="submit" value="Add!">
    </form>
    
</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Hero</title>
</head>
<body>
    <H1>This Hero Has Been Removed</H1>
    <ul>
        <h4>Superhero Name  - {{list_hero.name}}</h4>
        <h4>Superhero alter ego - {{list_hero.alter_ego}}</h4>
        <h4>Superhero Primary Ability  - {{list_hero.primary_ability}}</h4>
        <h4>Superhero Secondary Ability  - {{list_hero.secondary_ability}}</h4>
        <h4>Superhero Catch Phrase  - {{list_hero.catch_phrase}}</h4>
               
     </ul>
     <a href = "{%url 'superheroes:index' %}">Return Home</a>
    
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Details</title>
</head>
<body>
    <a href = "{%url 'superheroes:index' %}">Home</a>
    <ul>
        <h4>Superhero Name  - {{single_hero.name}}</h4>
        <h4>Superhero alter ego - {{single_hero.alter_ego}}</h4>
        <h4>Superhero Primary Ability  - {{single_hero.primary_ability}}</h4>
        <h4>Superhero Secondary Ability  - {{single_hero.secondary_ability}}</h4>
        <h4>Superhero Catch Phrase  - {{single_hero.catch_phrase}}</h4>
               
     </ul>
     <a href = "{%url 'superheroes:edit' single_hero.id %}">Edit Details</a>
       

    
</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Heros Details</title>
</head>
<body>
    

    <a href = "{%url 'superheroes:index' %}">Home</a>


    <form action = "{%url 'superheroes:edit' hero_to_update.id %}" method ="post">
        {%csrf_token %}

    Name:<input type ='text' name="name" id="name" value ='{{hero_to_update.name}}'><br />
    Atler Ego:<input type ='text' name="alter_ego" id="alter_ego" value ='{{hero_to_update.alter_ego}}'><br />
    Primary Ability:<input type ='text' name="primary" id="primary"value ='{{hero_to_update.primary_ability}}'><br />
    Secondary Ability:<input type ='text' name="secondary" id="secondary"value ='{{hero_to_update.secondary.ability}}'><br />
    Catch Phrase:<input type ='text' name="catchphrase" id="catchprase"value ='{{hero_to_update.catch_phrase}}'><br />
        <input type="submit" value="CHANGE!">



    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Superheroes</title>
  </head>
  <body>
      <div class="container">
    <h1>These are your Superheroes!!</h1>
    <div class='row row row-cols-3'>
    <div class="col-6 "><ul>
        {%for hero in all_heroes %}
        <li><h4>{{hero.name}}</h4> 
            <div class="col-6 "><h5><a href = "{%url 'superheroes:detail' hero.id %}">View Hero Details</a></h5></div>
            <div class="col-6 "><h5><a href = "{%url 'superheroes:delete' hero.id %}">Delete This Hero</a></h5></div></li>
        {%endfor%}
        </ul>
        </div>
</div>
        <a href = "{%url 'superheroes:create' %}">Create New Hero</a>

        <h1>My Fav Superhero</h1>
    <br>
    {% load static %} <img src = "{% static 'admin/img/Deadpool.jpg' %}" width = 600 height = 400 alt ="DEADPOOL">
        

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</div>
</div>
  </body>
</html>